name = "mundial-predicciones"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "MATCHES_CACHE"
id = "36556db281e34b148ede9a4572aab45a"

